# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-24 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('lang', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.IntegerField(choices=[(-4, 'Submitted'), (-3, 'Waiting'), (-2, 'Judging'), (-1, 'Wrong Answer'), (0, 'Accepted'), (1, 'Time Limit Exceeded'), (2, 'Idleness Limit Exceeded'), (3, 'Memory Limit Exceeded'), (4, 'Runtime Error'), (5, 'System Error'), (6, 'Compile Error'), (7, 'Idleness Limit Exceeded'), (8, 'Time Limit Exceeded'), (11, 'Judge Error'), (12, 'Pretest Passed')], default=-3)),
                ('running_result', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
